In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [22]:
df = pd.read_csv("./data/Clean_Dataset.csv")
print(f"Airline price analysis: {df.shape[0]} rows and {df.shape[1]} columns")
display(df.head())

Airline price analysis: 300153 rows and 12 columns

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   flight            300153 non-null  str
 3   source_city       300153 non-null  str
 4   departure_time    300153 non-null  str
 5   stops             300153 non-null  str
 6   arrival_time      300153 non-null  str
 7   destination_city  300153 non-null  str
 8   class             300153 non-null  str
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(8)
memory usage: 27.5 MB

In [24]:
df.drop(columns= 'Unnamed: 0', inplace= True)

In [25]:
df

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [26]:
df.isnull().sum()

airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.describe()

            duration      days_left          price
count  300153.000000  300153.000000  300153.000000
mean       12.221021      26.004751   20889.660523
std         7.191997      13.561004   22697.767366
min         0.830000       1.000000    1105.000000
25%         6.830000      15.000000    4783.000000
50%        11.250000      26.000000    7425.000000
75%        16.170000      38.000000   42521.000000
max        49.830000      49.000000  123071.000000

In [29]:
df['airline'].value_counts(ascending= True)

airline
SpiceJet       9011
AirAsia       16098
GO_FIRST      23173
Indigo        43120
Air_India     80892
Vistara      127859
Name: count, dtype: int64

In [30]:
df['stops'].value_counts()

stops
one            250863
zero            36004
two_or_more     13286
Name: count, dtype: int64

In [31]:
df['class'].value_counts(ascending= True)

class
Business     93487
Economy     206666
Name: count, dtype: int64

Does price vary with airlines?

In [32]:
avg_price_airline = df.groupby('airline', as_index= False).agg(avg_price=('price', 'mean')).sort_values(by='avg_price', ascending= False).round(2)
print("Average price by airline:")
avg_price_airline

Average price by airline:

     airline  avg_price
5    Vistara   30396.54
1  Air_India   23507.02
4   SpiceJet    6179.28
2   GO_FIRST    5652.01
3     Indigo    5324.22
0    AirAsia    4091.07

Does ticket price change based on departure time and arrival time?

In [33]:
avg_dept_price = df.groupby('departure_time', as_index= False).agg(avg_price=('price', 'mean')).sort_values(by='avg_price', ascending= False).round(2)
print("Average departure price:")
avg_dept_price

Average departure price:

  departure_time  avg_price
5          Night   23062.15
4        Morning   21630.76
2        Evening   21232.36
1  Early_Morning   20370.68
0      Afternoon   18179.20
3     Late_Night    9295.30

In [34]:
avg_arr_price = df.groupby('arrival_time', as_index= False).agg(avg_price=('price', 'mean')).sort_values(by='avg_price', ascending= False).round(2)
print("Average arrival price:")
avg_arr_price

Average arrival price:

    arrival_time  avg_price
2        Evening   23044.37
4        Morning   22231.08
5          Night   21586.76
0      Afternoon   18494.60
1  Early_Morning   14993.14
3     Late_Night   11284.91

How does price change with source and destination (route)?

In [39]:
df['destination_city'].unique()

<StringArray>
['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi']
Length: 6, dtype: str

In [40]:
df['source_city'].unique()

<StringArray>
['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai']
Length: 6, dtype: str

In [36]:
df["route"] = df["source_city"] + " - " + df["destination_city"]
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,route
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,Delhi - Mumbai
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,Delhi - Mumbai
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,Delhi - Mumbai
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,Delhi - Mumbai
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,Delhi - Mumbai

In [45]:
avg_route_price = df.groupby("route").agg(avg_price=('price', 'mean')).sort_values(by= 'avg_price', ascending=False)
avg_route_price

                          avg_price
route
Chennai - Bangalore    25081.850454
Kolkata - Chennai      23660.361040
Bangalore - Kolkata    23500.061229
Bangalore - Chennai    23321.850078
Mumbai - Bangalore     23147.873807
Bangalore - Mumbai     23128.618672
Mumbai - Chennai       22781.899112
Chennai - Mumbai       22765.849647
Kolkata - Bangalore    22744.808428
Chennai - Kolkata      22669.932407
Mumbai - Kolkata       22379.146723
Kolkata - Mumbai       22078.883579
Hyderabad - Chennai    21848.065989
Chennai - Hyderabad    21591.345404
Kolkata - Hyderabad    21500.011397
Hyderabad - Bangalore  21347.177998
Bangalore - Hyderabad  21226.121192
Mumbai - Hyderabad     21004.046705
Hyderabad - Kolkata    20823.893201
Delhi - Kolkata        20566.409418
Hyderabad - Mumbai     20080.865759
Kolkata - Delhi        19422.354559
Delhi - Chennai        19369.881354
Delhi - Mumbai         19355.829812
Chennai - Delhi        18981.863948
Mumbai - Delhi         18725.320008
Delhi - Bangalore      17880.216315
Bangalore - Delhi      17723.313972
Delhi - Hyderabad      17347.288379
Hyderabad - Delhi      17243.945685

In [46]:
print("Top 10 highest-priced routes:")
avg_route_price.head(10)

Top 10 highest-priced routes:

                        avg_price
route
Chennai - Bangalore  25081.850454
Kolkata - Chennai    23660.361040
Bangalore - Kolkata  23500.061229
Bangalore - Chennai  23321.850078
Mumbai - Bangalore   23147.873807
Bangalore - Mumbai   23128.618672
Mumbai - Chennai     22781.899112
Chennai - Mumbai     22765.849647
Kolkata - Bangalore  22744.808428
Chennai - Kolkata    22669.932407

How is price affected when tickets are bought close to departure?